{% set name = "somata" %}
{% set version = "0.5.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 090da5199b92fcc408b69ca977d8eecd93554120e7750016f9116d84f0e5713b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - cmdstanpy
    - codetiming
    - colorcet
    - joblib
    - kneed
    - matplotlib-base
    - mne >=1.6.0
    - numpy >=1.22
    - scipy
    - spectrum
    - tqdm
    - pandas
    - python >=3.8
    - pytorch >=1.12.1

test:
  requires:
    - pytest
  imports:
    - somata

about:
  home: https://github.com/mh105/somata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "State-space Oscillator Modeling And Time-series Analysis"
  doc_url: https://pypi.org/project/somata
  doc_source_url: https://github.com/mh105/somata/blob/main/README.md
  dev_url: https://github.com/mh105/somata

extra:
  recipe-maintainers:
    - mh105
