{% set name = "somata" %}
{% set version = "0.4.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 92450714664286b6e6f22479f78d9d7c58dcd50bcd4382d98e25666b6d59ee36

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - numpy >=1.22
    - torch>=1.12.1
    - codetiming
    - colorcet
    - joblib
    - kneed
    - matplotlib-base
    - mne
    - scipy
    - spectrum
    - tqdm

test:
  requires:
    - pytest
  imports:
    - somata

about:
  home: https://github.com/mh105/somata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "State-space Oscillator Modeling And Time-series Analysis"
  doc_url: https://pypi.org/project/somata/
  doc_source_url: https://github.com/mh105/somata-dev/blob/master/README.md
  dev_url: https://github.com/mh105/somata

extra:
  recipe-maintainers:
    - mh105
