{% set name = "somata" %}
{% set version = "0.5.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 675e1eecfbe9e3b4dead2e3bff56f08dfc6614f2ca6307f671ab0651a10a7e45

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - cmdstanpy
    - codetiming
    - colorcet
    - joblib
    - kneed
    - matplotlib-base
    - mne
    - numpy
    - scipy
    - spectrum
    - statsmodels
    - tqdm
    - pandas
    - python >=3.8
    - pytorch

test:
  requires:
    - pytest
  imports:
    - somata

about:
  home: https://github.com/mh105/somata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "State-space Oscillator Modeling And Time-series Analysis"
  doc_url: https://pypi.org/project/somata
  doc_source_url: https://github.com/mh105/somata/blob/main/README.md
  dev_url: https://github.com/mh105/somata

extra:
  recipe-maintainers:
    - mh105
